{% set name = "donfig" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c3759f9500acda430775666e2dae0146f25b1e37acf12c57e55344118a089c71

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - pyyaml
    - versioneer
  run:
    - python >=3.8
    - pyyaml

test:
  imports:
    - donfig
    - donfig.tests
  requires:
    - pytest
    - cloudpickle

about:
  home: https://github.com/pytroll/donfig
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python package for configuring a python package
  doc_url: https://donfig.readthedocs.io/en/latest/
  dev_url: https://github.com/pytroll/donfig

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - pnuu
    - adybbroe
    - mrocklin
    - jcrist
    - jhamman
